version: '3'

services:
  database-mysql:
    container_name: lol-database-mysql
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: 'lol'
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    ports:
      - '33306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

  database-adminer:
    container_name: lol-database-adminer
    image: adminer:latest
    ports:
      - "38080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: lol-database-mysql
      ADMINER_DESIGN: hydra
      ADMINER_PLUGINS: tables-filter tinymce

